In [1]:
import pandas as pd 
import numpy as np 

In [2]:
data=pd.read_csv("fetal_health.csv")

In [3]:
data.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [4]:
data.dtypes

baseline value                                            float64
accelerations                                             float64
fetal_movement                                            float64
uterine_contractions                                      float64
light_decelerations                                       float64
severe_decelerations                                      float64
prolongued_decelerations                                  float64
abnormal_short_term_variability                           float64
mean_value_of_short_term_variability                      float64
percentage_of_time_with_abnormal_long_term_variability    float64
mean_value_of_long_term_variability                       float64
histogram_width                                           float64
histogram_min                                             float64
histogram_max                                             float64
histogram_number_of_peaks                                 float64
histogram_

In [5]:
data.isnull().sum()

baseline value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                          

In [6]:
data.describe()

baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057                  0.000590   
min               0.000000              0.000000                  0.000000   
25%               0.000000              0.000000                  0.000000   
50%               0.000000              0.000000                  0.000000   
75%               0.003000              0.000000                  0.000000   
max               0.015000              0.001000                  0.005000   

       abnormal_short_term_variability  mean_value_of_short_term_variability  \
count                      2126.000000                           2126.000000   
mean                         46.990122                              1.332785   
std                          17.192814                              0.883241   
min                          12.000000                              0.200000   
25%                          32.000000                              0.700000   
50%                          49.000000                              1.200000   
75%                          61.000000                              1.700000   
max                          87.000000                              7.000000   

       percentage_of_time_with_abnormal_long_term_variability  ...  \
count                                         2126.00000       ...   
mean                                             9.84666       ...   
std                                             18.39688       ...   
min                                              0.00000       ...   
25%                                              0.00000       ...   
50%                                              0.00000       ...   
75%                                             11.00000       ...   
max                                             91.00000       ...   

       histogram_min  histogram_max  histogram_number_of_peaks  \
count    2126.000000    2126.000000                2126.000000   
mean       93.579492     164.025400                   4.068203   
std        29.560212      17.944183                   2.949386   
min        50.000000     122.000000                   0.000000   
25%        67.000000     152.000000                   2.000000   
50%        93.000000     162.000000                   3.000000   
75%       120.000000     174.000000                   6.000000   
max       159.000000     238.000000                  18.000000   

       histogram_number_of_zeroes  histogram_mode  histogram_mean  \
count                 2126.000000     2126.000000     2126.000000   
mean                     0.323612      137.452023      134.610536   
std                      0.706059       16.381289       15.593596   
min                      0.000000       60.000000       73.000000   
25%                      0.000000      129.000000      125.000000   
50%                      0.000000      139.000000      136.000000   
75%                      0.000000      148.000000      145.000000   
max                     10.000000      187.000000      182.000000   

       histogram_median  histogr

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [8]:
x = data.drop('fetal_health', axis=1)
y = data['fetal_health']

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(copy=True, feature_range=(0, 1))
X = scaler.fit_transform(x)

#showing data
print('x \n' , X[:10])
print('y \n' , y[:10])

x 
 [[0.25925926 0.         0.         0.         0.         0.
  0.         0.81333333 0.04411765 0.47252747 0.04733728 0.34463277
  0.11009174 0.03448276 0.11111111 0.         0.47244094 0.58715596
  0.40366972 0.27137546 1.        ]
 [0.48148148 0.31578947 0.         0.4        0.2        0.
  0.         0.06666667 0.27941176 0.         0.20512821 0.71751412
  0.16513761 0.65517241 0.33333333 0.1        0.63779528 0.57798165
  0.57798165 0.04460967 0.5       ]
 [0.5        0.15789474 0.         0.53333333 0.2        0.
  0.         0.05333333 0.27941176 0.         0.2642998  0.71751412
  0.16513761 0.65517241 0.27777778 0.1        0.63779528 0.56880734
  0.55963303 0.04832714 0.5       ]
 [0.51851852 0.15789474 0.         0.53333333 0.2        0.
  0.         0.05333333 0.32352941 0.         0.45364892 0.6440678
  0.02752294 0.4137931  0.61111111 0.         0.60629921 0.55963303
  0.55045872 0.04832714 1.        ]
 [0.48148148 0.36842105 0.         0.53333333 0.         0.
  0.     

In [10]:
from sklearn.model_selection import train_test_split


In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=0)

In [12]:
print("x_train shape is:",x_train.shape)

x_train shape is: (2096, 21)


In [13]:
print("x_test shape is:",x_test.shape)


x_test shape is: (30, 21)


In [14]:
print("y_train shape is:",y_train.shape)


y_train shape is: (2096,)


In [15]:
print("y_test shape is:",y_test.shape)


y_test shape is: (30,)


In [16]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
RandomForestClassifierModel = RandomForestClassifier(criterion = 'gini',n_estimators=100,max_depth=4,random_state=33) #criterion can be also : entropy 
RandomForestClassifierModel.fit(x_train, y_train)

#Calculating Details
print('RandomForestClassifierModel Train Score is : ' , RandomForestClassifierModel.score(x_train, y_train))
print('RandomForestClassifierModel Test Score is : ' , RandomForestClassifierModel.score(x_test, y_test))
print('RandomForestClassifierModel features importances are : ' , RandomForestClassifierModel.feature_importances_)
print('----------------------------------------------------')

#Calculating Prediction
y_pred = RandomForestClassifierModel.predict(x_test)
y_pred_prob = RandomForestClassifierModel.predict_proba(x_test)
print('Predicted Value for RandomForestClassifierModel is : ' , y_pred[:10])
print('Prediction Probabilities Value for RandomForestClassifierModel is : ' , y_pred_prob[:10])

RandomForestClassifierModel Train Score is :  0.9141221374045801
RandomForestClassifierModel Test Score is :  0.9666666666666667
RandomForestClassifierModel features importances are :  [0.03172369 0.06103808 0.00635358 0.03242506 0.00561184 0.00029729
 0.052399   0.16621254 0.14490848 0.12023168 0.02689315 0.02867139
 0.03870214 0.01332403 0.00477523 0.00044131 0.05309124 0.11922952
 0.05987562 0.03210202 0.00169313]
----------------------------------------------------
Predicted Value for RandomForestClassifierModel is :  [1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
Prediction Probabilities Value for RandomForestClassifierModel is :  [[0.9356008  0.05456451 0.00983469]
 [0.96424182 0.02731421 0.00844397]
 [0.89345021 0.09442225 0.01212754]
 [0.44089584 0.460601   0.09850315]
 [0.25153197 0.64429171 0.10417632]
 [0.93925867 0.05511488 0.00562645]
 [0.87927957 0.06067046 0.06004997]
 [0.9112483  0.07468098 0.01407073]
 [0.94845818 0.03860466 0.01293715]
 [0.40557513 0.49780358 0.09662128]]


In [21]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
DecisionTreeClassifierModel = DecisionTreeClassifier(criterion='gini',max_depth=2,random_state=33) #criterion can be entropy
DecisionTreeClassifierModel.fit(x_train, y_train)

#Calculating Details
print('DecisionTreeClassifierModel Train Score is : ' , DecisionTreeClassifierModel.score(x_train, y_train))
print('DecisionTreeClassifierModel Test Score is : ' , DecisionTreeClassifierModel.score(x_test, y_test))
print('DecisionTreeClassifierModel Classes are : ' , DecisionTreeClassifierModel.classes_)
print('DecisionTreeClassifierModel feature importances are : ' , DecisionTreeClassifierModel.feature_importances_)
print('----------------------------------------------------')

#Calculating Prediction
y_pred = DecisionTreeClassifierModel.predict(x_test)
y_pred_prob = DecisionTreeClassifierModel.predict_proba(x_test)
print('Predicted Value for DecisionTreeClassifierModel is : ' , y_pred[:10])
print('Prediction Probabilities Value for DecisionTreeClassifierModel is : ' , y_pred_prob[:10])

DecisionTreeClassifierModel Train Score is :  0.8826335877862596
DecisionTreeClassifierModel Test Score is :  0.9333333333333333
DecisionTreeClassifierModel Classes are :  [1. 2. 3.]
DecisionTreeClassifierModel feature importances are :  [0.         0.         0.         0.         0.         0.
 0.         0.         0.49462716 0.12079252 0.         0.
 0.         0.         0.         0.         0.         0.38458032
 0.         0.         0.        ]
----------------------------------------------------
Predicted Value for DecisionTreeClassifierModel is :  [1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
Prediction Probabilities Value for DecisionTreeClassifierModel is :  [[0.93423479 0.05654579 0.00921942]
 [0.93423479 0.05654579 0.00921942]
 [0.93423479 0.05654579 0.00921942]
 [0.30721003 0.61442006 0.07836991]
 [0.30721003 0.61442006 0.07836991]
 [0.93423479 0.05654579 0.00921942]
 [0.93423479 0.05654579 0.00921942]
 [0.93423479 0.05654579 0.00921942]
 [0.93423479 0.05654579 0.00921942]
 [0.307210

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
#Calculating Accuracy Score  : ((TP + TN) / float(TP + TN + FP + FN))
AccScore = accuracy_score(y_test, y_pred, normalize=False)
print('Accuracy Score is : ', AccScore)

Accuracy Score is :  28


In [30]:
from sklearn.metrics import f1_score
#Calculating F1 Score  : 2 * (precision * recall) / (precision + recall)
# f1_score(y_true, y_pred, labels=None, pos_label=1, average=’binary’, sample_weight=None)

F1Score = f1_score(y_test, y_pred, average='micro') #it can be : binary,macro,weighted,samples
print('F1 Score is : ', F1Score)

F1 Score is :  0.9333333333333333
